### PR TITLE
removed LabeledPoint from Python LDA internals

### PR DESCRIPTION
**Pull request by jkbradley**
Please review, and feel free to either merge or take what you need.

### CODE REVIEW

**Comment by yu-iskw** [comment]
One thing. we can't use `L` to express a long integer in Python 3.4. How should we support long integers in both of Python 2.x and Python 3.x?

"All integers are implemented as “long” integer objects of arbitrary size."
https://docs.python.org/3/c-api/long.html

```
$ python3.4

Python 3.4.2 (default, Jun 13 2015, 00:21:09)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1L
  File "<stdin>", line 1
    1L
     ^
SyntaxError: invalid syntax
```

**Comment by yu-iskw** [comment]
I have done a survey about in` type long int type in python2.6/python3.4 which were treated in Java. 

According to my research, if we want to deal with long int for the document index in LDA, we should go with `LabeledPoint` or such a new class. Because, it is quite difficulat to terat int and long int between python2.6/python3.4 and Java. Could you please check my experiment about that as follows.

https://gist.github.com/yu-iskw/12e92c2d718ca41dea90

Thanks
Yu

**Comment by jkbradley** [comment]
@yu-iskw I left a few comments on the survey about type conversions for Python versions.  Thank you for researching that so thoroughly!  I don't think I have answers for all of your comments.

These complexities make me wonder if we should go through the DataFrame API instead.  Perhaps the Python RDD can be converted into a DataFrame, which can be passed to the Java stub for LDA.  That way, you can rely on DataFrame SerDe for type conversions, and that should be robust and well-tested.

**Comment by yu-iskw** [comment]
@jkbradley thank you for your feedback. That's a good idea! Using the DataFrame API would be nice. I'll try it!
I think if the DataFrame API doesn't work about type conversions, we should go with LabeledPoint or create a wrapper class.
Thanks!

**Pull request closed without merging**
